app:
  name: app
  port: :8080
mysql:
  user: root
  password: *****
  host: 127.0.0.1
  port: 3306
  db: default
redis:
  host: 127.0.0.1
  port: 6379
  db: 1
logger:
  level: debug  #日志记录级别 debug,info,warn,error  
  filename: ./log/app.log     #日志文件的位置
  gormFile: ./log/gorm.log     #日志文件的位置
  maxSize: 5              #文件最大尺寸（以MB为单位）
  maxBackups: 0           #保留的最大旧文件数量
  maxAge: 0               #保留旧文件的最大天数
database:
  db1:
    dsname: db1
    username: user
    password: password
    host: 127.0.0.1
    port: 3306
    database: db
  db2:
    dsname: db2
    username: user
    password: password
    host: 127.0.0.1
    port: 3306
    database: db
